---
- name: Deploy WordPress and configure server
  hosts: all
  become: true

  vars:
    server_name: test.simonhaddadgervais.com
    wordpress_home: /home/simonhaddadgervais/public_html

  tasks:

    - name: Upgrade system packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install mysql nginx php and monit
      apt:
        name:
          - mysql-server-8.0
          - libmysqlclient-dev
          - nginx
          - php-mysql
          - php-fpm
          - monit
          - php-curl
          - php-common
          - php-imagick
          - php-mbstring
          - php-xml
          - php-zip
          - php-json
          - php-xmlrpc
          - php-gd
          - unzip
          - python3-pymysql
        state: present

    - name: create cache
      file:
        path: /usr/share/nginx/cache
        state: directory

    - name: create fcgi
      file:
        path: /usr/share/nginx/cache/fcgi
        state: directory

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - php7.4-fpm
        - mysql

    - name: Create user for website
      user:
        name: simonhaddadgervais
        shell: /bin/bash
        home: /home/simonhaddadgervais

    - name: Create logs directory
      file:
        path: /home/simonhaddadgervais/logs
        state: directory
        owner: simonhaddadgervais
        group: www-data

    - name: Create phpfpm_error.log
      file:
        path: /home/simonhaddadgervais/logs/phpfpm_error.log
        state: touch
        owner: simonhaddadgervais

    - name: Remove old pool conf
      file:
        path: /etc/php/8.1/fpm/pool.d/www.conf
        state: absent

    - name: Remove default nginxconfig file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Configure Nginx
      template:
          src: nginx.conf.j2
          dest: /etc/nginx/nginx.conf
          owner: root
          group: root
          mode: '0644'

    - name: Configure Nginx vhost
      template:
        src: nginx_wordpress_vhost.conf
        dest:  /etc/nginx/conf.d/simonhaddadgervais.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

    - name: Configure PHP-fpm
      template:
          src: php-fpm.conf.j2
          dest: /etc/php/7.4/fpm/pool.d/simonhaddadgervais.conf
          owner: root
          group: root
          mode: '0644'
      notify: Restart PHP-FPM

    - name: Set the root password
      mysql_user:
        name: root
        password: rootpassword
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creating wordpress DB with the Root User
      mysql_db:
        name: simonhaddadgervais
        state: present
        login_user: root
        login_password: rootpassword

    - name: Creating wordpress user and give him all privileges on wordpress db
      mysql_user:
        name: simonhaddadgervais
        password: dbpassword
        state: present
        priv: "*.*:ALL"
        login_user: root
        login_password: rootpassword

    - name: Check if public_html directory exists
      stat:
        path: /home/simonhaddadgervais/public_html
      register: public_html_check

    - name: Unzip WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /home/simonhaddadgervais/
        remote_src: yes
        owner: simonhaddadgervais
        group: www-data
        mode : 0755
      when: not public_html_check.stat.exists

    - name: Move WordPress files to public_html
      command: mv /home/simonhaddadgervais/wordpress /home/simonhaddadgervais/public_html
      when: not public_html_check.stat.exists
      notify: 
        - Restart PHP-FPM
        - Restart Nginx
      
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      service:
        name: php7.4-fpm
        state: restarted
