---
- name: Deploy WordPress Website
  hosts: all
  gather_facts: true
  become: true

  roles:
    - common
    - webserver
    - mysql
    - wordpress
    - monitoring

  tasks:
    
  - name: Restart services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    loop:
      - nginx
      - php7.4-fpm
      - monit
