---

- name: Copy monit website config
  copy:
    src: wordpress.cnf.j2
    dest: /etc/monit/conf-available/wordpress.cnf

- name: Copy monit configuration
  copy:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    mode: '0600'

