---
- name: Change permissions for /etc/monit/monitrc
  file:
    path: /etc/monit/monitrc
    mode: '0600'

- name: COnfigure certbot
  shell: "certbot --nginx --non-interactive --agree-tos -m {{email}} -d {{website}}"
