---
- name: Check if the root password is previously set or NOT
  shell: mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: root_pwd_check.rc == 0

- name: Creating wordpress DB with the Root User
  mysql_db:
    name: simonhaddadgervais
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Creating wordpress user and give him all privileges on wordpress db
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    state: present
    priv: "*.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  changed_when: false
