---
- name: Upgrade system packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install packages and extensions
  apt:
    name: "{{ item }}"
  loop: "{{ php_modules + mysql + ['nginx', 'monit', 'unzip', 'certbot', 'python3-certbot-nginx'] }}"
  changed_when: false

- name: Create user for website
  user:
    name: simonhaddadgervais
    shell: /bin/bash
    home: /home/simonhaddadgervais
